# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Category.create!([
{ name: "community", url: "community"},
{ name: "services", url: "services"},
{ name: "discussion forums", url: "discussion"},
{ name: "housing", url: "housing"},
{ name: "for sale", url: "for-sale"},
{ name: "jobs", url: "jobs"},
{ name: "gigs", url: "gigs"},
{ name: "resumes", url: "resumes"}
])

Category.create!([
{ name: "activities", url: "", parent_id: 1 },
{ name: "artists", url: "", parent_id: 1 },
{ name: "childcare", url: "", parent_id: 1 },
{ name: "classes", url: "", parent_id: 1 },
{ name: "events", url: "", parent_id: 1 },
{ name: "general", url: "", parent_id: 1 },
{ name: "groups", url: "", parent_id: 1 },
{ name: "local news", url: "", parent_id: 1 },
{ name: "lost+found", url: "", parent_id: 1 },
{ name: "missed connections", url: "", parent_id: 1 },
{ name: "musicians", url: "", parent_id: 1 },
{ name: "pets", url: "", parent_id: 1 },
{ name: "politics", url: "", parent_id: 1 },
{ name: "rants & raves", url: "", parent_id: 1 },
{ name: "rideshare", url: "", parent_id: 1 },
{ name: "volunteers", url: "", parent_id: 1 }
])

Category.create!([
{ name: "automotive", url: "", parent_id: 2 },
{ name: "beauty", url: "", parent_id: 2 },
{ name: "cell/mobile", url: "", parent_id: 2 },
{ name: "computer", url: "", parent_id: 2 },
{ name: "creative", url: "", parent_id: 2 },
{ name: "cycle", url: "", parent_id: 2 },
{ name: "event", url: "", parent_id: 2 },
{ name: "farm+garden", url: "", parent_id: 2 },
{ name: "financial", url: "", parent_id: 2 },
{ name: "household", url: "", parent_id: 2 },
{ name: "labor/move", url: "", parent_id: 2 },
{ name: "legal", url: "", parent_id: 2 },
{ name: "lessons", url: "", parent_id: 2 },
{ name: "marine", url: "", parent_id: 2 },
{ name: "pet", url: "", parent_id: 2 },
{ name: "real estate", url: "", parent_id: 2 },
{ name: "skilled trade", url: "", parent_id: 2 },
{ name: "sm biz ads", url: "", parent_id: 2 },
{ name: "travel/vac", url: "", parent_id: 2 },
{ name: "write/ed/tran", url: "", parent_id: 2 }
])

Category.create!([
{ name: "android", url: "", parent_id: 3 },
{ name: "apple", url: "", parent_id: 3 },
{ name: "arts", url: "", parent_id: 3 },
{ name: "atheist", url: "", parent_id: 3 },
{ name: "autos", url: "", parent_id: 3 },
{ name: "beauty", url: "", parent_id: 3 },
{ name: "bikes", url: "", parent_id: 3 },
{ name: "celebs", url: "", parent_id: 3 },
{ name: "comp", url: "", parent_id: 3 },
{ name: "cosmos", url: "", parent_id: 3 },
{ name: "diet", url: "", parent_id: 3 },
{ name: "divorce", url: "", parent_id: 3 },
{ name: "dying", url: "", parent_id: 3 },
{ name: "eco", url: "", parent_id: 3 },
{ name: "feedbk", url: "", parent_id: 3 },
{ name: "film", url: "", parent_id: 3 },
{ name: "fixit", url: "", parent_id: 3 },
{ name: "food", url: "", parent_id: 3 },
{ name: "frugal", url: "", parent_id: 3 },
{ name: "gaming", url: "", parent_id: 3 },
{ name: "garden", url: "", parent_id: 3 },
{ name: "haiku", url: "", parent_id: 3 },
{ name: "help", url: "", parent_id: 3 },
{ name: "history", url: "", parent_id: 3 },
{ name: "housing", url: "", parent_id: 3 },
{ name: "jobs", url: "", parent_id: 3 },
{ name: "jokes", url: "", parent_id: 3 },
{ name: "legal", url: "", parent_id: 3 },
{ name: "linux", url: "", parent_id: 3 },
{ name: "manners", url: "", parent_id: 3 },
{ name: "marriage", url: "", parent_id: 3 },
{ name: "money", url: "", parent_id: 3 },
{ name: "music", url: "", parent_id: 3 },
{ name: "open", url: "", parent_id: 3 },
{ name: "outdoor", url: "", parent_id: 3 },
{ name: "parent", url: "", parent_id: 3 },
{ name: "pets", url: "", parent_id: 3 },
{ name: "philos", url: "", parent_id: 3 },
{ name: "photo", url: "", parent_id: 3 },
{ name: "politics", url: "", parent_id: 3 },
{ name: "psych", url: "", parent_id: 3 },
{ name: "recover", url: "", parent_id: 3 },
{ name: "religion", url: "", parent_id: 3 },
{ name: "rofo", url: "", parent_id: 3 },
{ name: "science", url: "", parent_id: 3 },
{ name: "spirit", url: "", parent_id: 3 },
{ name: "sports", url: "", parent_id: 3 },
{ name: "super", url: "", parent_id: 3 },
{ name: "tax", url: "", parent_id: 3 },
{ name: "travel", url: "", parent_id: 3 },
{ name: "tv", url: "", parent_id: 3 },
{ name: "vegan", url: "", parent_id: 3 },
{ name: "words", url: "", parent_id: 3 },
{ name: "writing", url: "", parent_id: 3 }
])

Category.create!([
{ name: "apts / housing", url: "", parent_id: 4 },
{ name: "housing swap", url: "", parent_id: 4 },
{ name: "housing wanted", url: "", parent_id: 4 },
{ name: "office / commercial", url: "", parent_id: 4 },
{ name: "parking / storage", url: "", parent_id: 4 },
{ name: "real estate for sale", url: "", parent_id: 4 },
{ name: "rooms / shared", url: "", parent_id: 4 },
{ name: "rooms wanted", url: "", parent_id: 4 },
{ name: "sublets / temporary", url: "", parent_id: 4 },
{ name: "vacation rentals", url: "", parent_id: 4 }
])

Category.create!([
{ name: "antiques", url: "", parent_id: 5 },
{ name: "appliances", url: "", parent_id: 5 },
{ name: "arts+crafts", url: "", parent_id: 5 },
{ name: "atv/utv/sno", url: "", parent_id: 5 },
{ name: "auto parts", url: "", parent_id: 5 },
{ name: "aviation", url: "", parent_id: 5 },
{ name: "baby+kid", url: "", parent_id: 5 },
{ name: "barter", url: "", parent_id: 5 },
{ name: "beauty+hlth", url: "", parent_id: 5 },
{ name: "bike parts", url: "", parent_id: 5 },
{ name: "bikes", url: "", parent_id: 5 },
{ name: "boat parts", url: "", parent_id: 5 },
{ name: "boats", url: "", parent_id: 5 },
{ name: "books", url: "", parent_id: 5 },
{ name: "business", url: "", parent_id: 5 },
{ name: "cars+trucks", url: "", parent_id: 5 },
{ name: "cds/dvd/vhs", url: "", parent_id: 5 },
{ name: "cell phones", url: "", parent_id: 5 },
{ name: "clothes+acc", url: "", parent_id: 5 },
{ name: "collectibles", url: "", parent_id: 5 },
{ name: "computer parts", url: "", parent_id: 5 },
{ name: "computers", url: "", parent_id: 5 },
{ name: "electronics", url: "", parent_id: 5 },
{ name: "farm+garden", url: "", parent_id: 5 },
{ name: "free", url: "", parent_id: 5 },
{ name: "furniture", url: "", parent_id: 5 },
{ name: "garage sale", url: "", parent_id: 5 },
{ name: "general", url: "", parent_id: 5 },
{ name: "heavy equip", url: "", parent_id: 5 },
{ name: "household", url: "", parent_id: 5 },
{ name: "jewelry", url: "", parent_id: 5 },
{ name: "materials", url: "", parent_id: 5 },
{ name: "motorcycle parts", url: "", parent_id: 5 },
{ name: "motorcycles", url: "", parent_id: 5 },
{ name: "music instr", url: "", parent_id: 5 },
{ name: "photo+video", url: "", parent_id: 5 },
{ name: "rvs+camp", url: "", parent_id: 5 },
{ name: "sporting", url: "", parent_id: 5 },
{ name: "tickets", url: "", parent_id: 5 },
{ name: "tools", url: "", parent_id: 5 },
{ name: "toys+games", url: "", parent_id: 5 },
{ name: "trailers", url: "", parent_id: 5 },
{ name: "video gaming", url: "", parent_id: 5 },
{ name: "wanted", url: "", parent_id: 5 },
{ name: "wheels+tires", url: "", parent_id: 5 }
])

Category.create!([
{ name: "accounting+finance", url: "", parent_id: 6 },
{ name: "admin / office", url: "", parent_id: 6 },
{ name: "arch / engineering", url: "", parent_id: 6 },
{ name: "art / media / design", url: "", parent_id: 6 },
{ name: "biotech / science", url: "", parent_id: 6 },
{ name: "business / mgmt", url: "", parent_id: 6 },
{ name: "customer service", url: "", parent_id: 6 },
{ name: "education", url: "", parent_id: 6 },
{ name: "etc / misc", url: "", parent_id: 6 },
{ name: "food / bev / hosp", url: "", parent_id: 6 },
{ name: "general labor", url: "", parent_id: 6 },
{ name: "government", url: "", parent_id: 6 },
{ name: "human resources", url: "", parent_id: 6 },
{ name: "legal / paralegal", url: "", parent_id: 6 },
{ name: "manufacturing", url: "", parent_id: 6 },
{ name: "marketing / pr / ad", url: "", parent_id: 6 },
{ name: "medical / health", url: "", parent_id: 6 },
{ name: "nonprofit sector", url: "", parent_id: 6 },
{ name: "real estate", url: "", parent_id: 6 },
{ name: "retail / wholesale", url: "", parent_id: 6 },
{ name: "sales / biz dev", url: "", parent_id: 6 },
{ name: "salon / spa / fitness", url: "", parent_id: 6 },
{ name: "security", url: "", parent_id: 6 },
{ name: "skilled trade / craft", url: "", parent_id: 6 },
{ name: "software / qa / dba", url: "", parent_id: 6 },
{ name: "systems / network", url: "", parent_id: 6 },
{ name: "technical support", url: "", parent_id: 6 },
{ name: "transport", url: "", parent_id: 6 },
{ name: "tv / film / video", url: "", parent_id: 6 },
{ name: "web / info design", url: "", parent_id: 6 },
{ name: "writing / editing", url: "", parent_id: 6 }
])

Category.create!([
{ name: "computer", url: "", parent_id: 7 },
{ name: "creative", url: "", parent_id: 7 },
{ name: "crew", url: "", parent_id: 7 },
{ name: "domestic", url: "", parent_id: 7 },
{ name: "event", url: "", parent_id: 7 },
{ name: "labor", url: "", parent_id: 7 },
{ name: "talent", url: "", parent_id: 7 },
{ name: "writing", url: "", parent_id: 7 }
])
